language: python
sudo: false

branches:
  only:
    - main

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luafilesystem
  - luarocks install busted
  - luarocks install luacheck

script:
  - luacheck src
